# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db:
    image: postgres
    command: postgres -p ${DRC_DB_PORT:-5440}
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=zac.conf.docker
      - SECRET_KEY=${SECRET_KEY}
      - DB_PORT
    ports:
      - 8081:8080
    depends_on:
      - db
